LOG_PATH: "logs"

MAX_RESULTS: 20

SENTIMENT_ANALYSIS_TASK: "sentiment-analysis"
# SENTIMENT_ANALYSIS_MODEL: "distilbert-base-uncased-finetuned-sst-2-english"
SENTIMENT_ANALYSIS_MODEL: "tabularisai/multilingual-sentiment-analysis"

PIPELINE_SENTIMENT_THRESHOLD: 0.3   # 30% negative mentions triggers alert